// Generated by SecretKey.swift.gyb
import Foundation

public struct SecretKey {

  public static let mercuryClientID: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let mercuryClientSecret: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let feedlyClientID: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let feedlyClientSecret: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let inoreaderAppID: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()

  public static let inoreaderAppKey: String = {
     let encoded: [UInt8] = [
      ]

      return decode(encoded)
  }()
}

private let salt: [UInt8] = [
  0x59, 0x64, 0x93, 0xd1, 0xe7, 0x17, 0xa5, 0x67, 
  0xae, 0x79, 0xcd, 0x0d, 0x51, 0xfc, 0xe5, 0xe4, 
  0x00, 0x3d, 0x5c, 0x52, 0x33, 0xb1, 0xab, 0x2c, 
  0xb2, 0x2c, 0x1b, 0x04, 0xd5, 0x02, 0x3f, 0x5b, 
  0xe4, 0x50, 0x94, 0xc8, 0xe9, 0x1c, 0x7c, 0x63, 
  0x0c, 0x88, 0x7f, 0x53, 0x57, 0x19, 0x2d, 0x06, 
  0xcd, 0x4b, 0x9b, 0xa5, 0x84, 0xc4, 0x10, 0x7f, 
  0x8a, 0x59, 0x09, 0x1e, 0x95, 0xb7, 0x40, 0x6e, 
]

private func decode(_ encoded: [UInt8]) -> String {
  String(decoding: encoded.enumerated().map { (offset, element) in
      element ^ salt[offset % salt.count]
  }, as: UTF8.self)
}
