  platform :ios, '13.0'

target 'PesoPlus' do
  use_frameworks!
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'AAINetwork', :http => 'https://prod-guardian-cv.oss-ap-southeast-5.aliyuncs.com/sdk/iOS-libraries/AAINetwork/AAINetwork-V1.0.2.tar.bz2', type: :tbz
  pod 'AAILiveness', :http => 'https://prod-guardian-cv.oss-ap-southeast-5.aliyuncs.com/sdk/iOS-liveness-detection/3.1.1/iOS-Liveness-SDK-V3.1.1.tar.bz2', type: :tbz

  post_install do |installer|
     bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
     def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
       framework_path = File.join(Dir.pwd, framework_relative_path)
       command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
       puts "Stripping bitcode: #{command}"
       system(command)
     end
     framework_paths = [
       "/Pods/AAINetwork/AAINetwork.xcframework/ios-arm64_armv7/AAINetwork.framework/AAINetwork",
       "/Pods/AAILiveness/AAILivenessSDK/AAILivenessSDK.xcframework/ios-arm64_armv7/AAILivenessSDK.framework/AAILivenessSDK",
     ]
     framework_paths.each do |framework_relative_path|
       strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
     end
   end

end
